Mylin/#187 improve spectral line query
CARTAvis/carta-backend-ICD-test pull request #193
Opened 2021-02-24 06:22 UTC by acdo2002

Fixed #187 
Each spectral line query has its own session, then it could prevent the sequence disorder. 
Improve the OpenFile to fit the upgrade CLIENT.ts

2021-02-24 07:31 UTC, ajm-asiaa commented
Only this part in SPECTRAL_LINE_QUERY_WIDE_FREQ.test.ts doesn't seem to consistently pass, even after increasing "spectralLineRequestWide" to 40000.

 ✕ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 40000ms (40007ms)
But sometimes it passes quickly:

✓ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 40000ms (15661ms)
✓ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 30000ms (29570ms)
Could it be a slow network sometimes? I'm not sure how it could be fixed.

2021-02-24 07:36 UTC, zarda requested changes
SPECTRAL_LINE_QUERY_WIDE_FREQ sometimes fails, which might relate to internet bandwidth.

2021-02-24 07:36 UTC, zarda commented on src/test/CLIENT.ts
> +                        ack.SpectralLineResponse.push(data);
Should have a 'break' in the end of case.

2021-02-24 07:36 UTC, zarda commented on src/test/CLIENT.ts
> +                        ack.SpectralLineResponse.push(data);
The client.stream() might need the similar codes.

2021-02-24 07:36 UTC, zarda commented on src/test/SPECTRAL_LINE_QUERY_WIDE_FREQ.test.ts
>              let response: CARTA.SpectralLineResponse;
```
let response: AckStream;
```

2021-02-24 07:49 UTC, acdo2002 commented
@zarda I have modify these two files based on your suggestions!

2021-02-24 08:16 UTC, ajm-asiaa approved these changes
`SPECTRAL_LINE_QUERY_WIDE_FREQ.test.ts` seems to run more reliably now. It passed in 5 out of 5 consecutive tests.

2021-02-25 05:49 UTC, zarda approved these changes

2021-02-25 05:49 UTC, merged