Update for new implement
CARTAvis/carta-backend-ICD-test pull request #211
Opened 2021-03-16 09:42 UTC by zarda

Update for #208, to adapt to a new implement in [#771](https://github.com/CARTAvis/carta-backend/pull/771).

2021-03-17 06:09 UTC, acdo2002 requested changes
expect(importRegionAckProperties[importRegionAckProperties.length - 1]).toEqual(String(Region.assertRegionId.id));

should be
expect(importRegionAckProperties[Region.assertRegionId.index]).toEqual(String(Region.assertRegionId.id));

2021-03-17 06:09 UTC, acdo2002 commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
>                  lengthOfRegions: 7,
should be lengthOfRegions: 8,

2021-03-17 06:09 UTC, acdo2002 commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
>                  lengthOfRegions: 7,
should be lengthOfRegions: 8,

2021-03-17 06:09 UTC, acdo2002 commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
> +                    id: 22,
should be id: 23,

2021-03-17 06:34 UTC, zarda commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
>                  lengthOfRegions: 7,
Correct

2021-03-17 06:34 UTC, zarda commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
>                  lengthOfRegions: 7,
correct

2021-03-17 06:40 UTC, zarda commented on src/test/CASA_REGION_IMPORT_EXPORT.test.ts
> +                    id: 22,
got it

2021-03-18 08:30 UTC, zarda commented
@ajm The demo building for branch 610_line_region went wrong so this testing will fail at the moment. Thought this testing could pass on a local instance.

2021-03-19 01:42 UTC, ajm-asiaa commented
@zarda It seems to be OK now. Works fine on MacOS against the `pam/610_line_region` backend branch.

2021-03-19 07:46 UTC, merged