Mylin/#184 improve region histogram for rotated ellipse
CARTAvis/carta-backend-ICD-test pull request #217
Opened 2021-03-30 05:49 UTC by acdo2002

Fixed #184 , adding one region histogram test to cover the [backend issue #689](https://github.com/CARTAvis/carta-backend/issues/689). 
The new implemented test would NOT PASS with the CARTA 1.4release backend. (Expected behavior)
But it can PASS with the current CARTA dev backend.

2021-03-30 07:07 UTC, zarda requested changes

2021-03-30 07:07 UTC, zarda commented on src/test/REGION_HISTOGRAM_ITERATION.test.ts
> +let testServerUrl = config.serverURL0;
testServerUrl = config.serverURL;

2021-03-30 07:07 UTC, zarda commented on src/test/REGION_HISTOGRAM_ITERATION.test.ts
> +            await Connection.streamUntil((type, data) => type == CARTA.RasterTileSync ? data.endSync : false);
Sorry about bad old code, better to be
```
await Connection.streamUntil((type, data) => type == CARTA.RasterTileSync && data.endSync);
```

2021-03-30 10:14 UTC, ajm-asiaa approved these changes

2021-03-31 07:43 UTC, zarda approved these changes

2021-03-31 07:43 UTC, merged